### ISSUE TITLE
Aptana stand-alone 3.6.0 pydev not working properly Mac 10.8.5

### ISSUE THREAD

**Issue by vertazzar** [aptana/studio3#223]
Performed update on Aptana 3.4.2
all works properly except pydev and this https://github.com/aptana/studio3/issues/220
- pydev
  - default theme is totally messed up
  - it shows errors (variable does not exist) for built-in variables like None, list, str...
  - code completion does not work, it says Port not bound (found port -1) e.g.
    import os
    os.path => you get error Port not bound (found port -1)

I read somewhere that pydev 3.0 in general has problems with mac

**Comment by BidiM** [comment]
Still 3.6.1 on Mac. Same problem.
