### ISSUE TITLE
[FEATURE REQUEST] Angularjs plugin

### ISSUE THREAD

**Issue by crooksey** [aptana/studio3#43]
I have googled and searched forums and haven't been able to find any support for angularjs, I'm not sure if this is the correct way to request new features, so apologise if this is in the wrong place.

**Comment by SunMedley** [comment]
Oh, man. This feature was requested in 2012. Is there any chance we get an AngularJS plug-in or bundle?

**Comment by joebordes** [comment]
+1

**Comment by paulvi** [comment]
just read above

**Comment by Gigi-DS** [comment]
+1

**Comment by paulvi** [comment]
Where is Angularjs plugin for Aptana?
