### ISSUE TITLE
Aptana Studio 3 failed install

### ISSUE THREAD

**Issue by jules777** [aptana/studio3#432]
I am attempting to install the program on my Windows system. I continue to get a "Failed to correctly acquire installer_nodejs_windows.msi file: CRC error." message. I have the current nodejs program installed.

**Comment by lamp5** [comment]
Hmmm?? 
https://stackoverflow.com/questions/33364694/product-aptana-studio-error-4155-failed-to-correctly-acquire-installer-node

**Comment by japanann** [comment]
Same here. Download fails on both Mac (both Intel and 64Bit) and Windows.

**Comment by jules777** [comment]
Aptana was recommended in a textbook for a javascript/jquery class. I could never get it to install so I am using another IDE and it works great. Unless it's required, there are many others with better features.

**Comment by nickfs000** [comment]
@jules777 what other IDEs work on Mac for this? thx

**Comment by jules777** [comment]
I work on Windows, so I don't know what's available for Mac, but I have been doing all my javascript/jquery programs on Notepad++ and testing in Chrome.

**Comment by ravenmarire13** [comment]
@nickfs000 

try some of these IDEs:
brackets - brackets.io
notepad++ - https://notepad-plus-plus.org/download/v7.5.4.html
xcode from apple  - https://developer.apple.com/xcode/downloads/
textwrangler - https://itunes.apple.com/us/app/textwrangler/id404010395?mt=12
textmate - https://textmate.en.softonic.com/mac (free trial...?)

**Comment by jules777** [comment]
Thank you @nickfs000. I have found that notepad++ is very simple to use for javascript. I've started using VisualCode [https://code.visualstudio.com/] and I really like it. It's nice that it has a built in command line too.

**Comment by ingo** [comment]
This has been fixed: https://github.com/aptana/studio3/releases/tag/3.7.1.201807271936
