### ISSUE TITLE
Aptana Studio fails to start or install on MAC Siera

### ISSUE THREAD

**Issue by allamiro** [aptana/studio3#449]
I m attaching the crash report  my video driver card has the latest updates 
[macapatanacrash.txt](https://github.com/aptana/studio3/files/1621730/macapatanacrash.txt)

**Comment by luc-j-bourhis** [comment]
I see the same crash with Aptana version 3.6.1.201712041219, on a 64-bit machine (@allamiro has a 32-bit machine judging from his bug report): MacPro 5,1 with 6-core Xeons, 24 GB of RAM, AMD Radeon R9 280x, running MacOS 10.12.6.

**Comment by ingo** [comment]
Please try the latest installers: https://github.com/aptana/studio3/releases/tag/3.7.0.201807190852
