### ISSUE TITLE
Cannot download for eclipse

### ISSUE THREAD

**Issue by carolcoral** [aptana/studio3#453]
the download button is not working,when i put it down ,nothing happen.i want to install it for my mac of eclipse. how to solve? thx.

when i install it in my eclipse,it tips me that there is noting can be fined.
i had put this URL:http://download.aptana.com/studio3/plugin/install

eclipse:4.7.2

and i want to install aptana 3.6.1

**Comment by frazei** [comment]
I think they're messing up all the repositories. A few months ago I found this working repository:
http://download.axway.com/aptana/studio3/php/update/stable
But now is not working anymore.
The only one that's still working is this:
http://preview.appcelerator.com/studio/
where you can download the 3.6.0 version...

**Comment by carolcoral** [comment]
@frazei thank you for your answer,i had changed another mirror to do it.But thank you any way

**Comment by frazei** [comment]
URL?

Il ven 22 giu 2018, 11:47 Carol <notifications@github.com> ha scritto:

**Comment by carolcoral** [comment]
@frazei no,i had used another Tools,not this.

**Comment by skullwritter** [comment]
Here are the URL's
https://preview.appcelerator.com/aptana/studio3/php/update/stable
https://preview.appcelerator.com/aptana/studio3/ruby/update/stable
https://preview.appcelerator.com/aptana/studio3/pydev/update/stable
