### ISSUE TITLE
SHA-256 checksum changed for installer .dmg file (version 3.6.1)

### ISSUE THREAD

**Issue by gtmgianni** [aptana/studio3#459]
The SHA-256 checksum for the `.dmg` file for version 3.6.1 of Aptana Studio has changed, without there being a version bump. I'm referring to the `.dmg` file currently available on this repository's "Releases" page, not the one provided on the www.aptana.com website (that download link seems to be broken?).

I'd just like to confirm ([for the purpose of this pull request](https://github.com/caskroom/homebrew-cask/pull/45592)) that this modification of the `.dmg` file was intentional? Thanks.

**Comment by brianmorton** [comment]
@sgtcoolguy @ingo

**Comment by gtmgianni** [comment]
@ingo Thanks for the confirmation.
