### ISSUE TITLE
Cannot start 3.6.1.GA under High Sierra

### ISSUE THREAD

**Issue by timwhitlock** [aptana/studio3#462]
Hello.

On macOS 10.13.4 I cannot launch the latest release installed from the [.dmg here](https://github.com/aptana/studio3/releases/tag/v3.6.1). The [crash report](https://pastebin.com/raw/gGAgjTZc) shows a seg fault.

I'm aware of the trick mentioned in issue #392 and other places. This doesn't work for me, although it gets further. The "Select a Workspace" dialogue comes up, but cannot be focused. 

I have an old version of v3.6.0 installed, which still works but can't be updated. I'm keen to upgrade for PHP 7 support, so help appreciated.

**Comment by IPSportal** [comment]
Hi

Same issue here, get as far as select a workspace but no further. Tried upgrading to latest Java, no avail.

**Comment by may2190** [comment]
Hi I 'm run in 10.13.5 run same problem cannot create or select location in workspace.

**Comment by ingo** [comment]
Please try the latest installers: https://github.com/aptana/studio3/releases/tag/3.7.0.201807190852

**Comment by timwhitlock** [comment]
I'm sorry to say that in the two months it took for a reply I purchased phpStorm. I would have loved to keep using Aptana as it served me well for many years.
