### ISSUE TITLE
Installation failed to install because of newer NodeJS 

### ISSUE THREAD

**Issue by richard-scott** [aptana/studio3#463]
I have just attempted to install the IDE and it failed because I already have Node.js installed.
I get these errors.
![2018-05-15 09_37_11-window](https://user-images.githubusercontent.com/5149834/40046037-d18e6516-5823-11e8-998c-4d8d0a681a8b.png)
![2018-05-15 09_37_26-window](https://user-images.githubusercontent.com/5149834/40046040-d303cd5a-5823-11e8-8e7b-a18a6ffaa853.png)
![2018-05-15 09_37_38-window](https://user-images.githubusercontent.com/5149834/40046042-d4831bea-5823-11e8-810c-72fd59e57680.png)

**Comment by adamtbak** [comment]
I was having the same problem, what worked for me was to install the file from the command line using two extra options. First "cd" to your directory containing your install file, then launch the install file using the following options "/passive /norestart". So if your Aptana install file was named, "AptanaInstall", you would type the following into your command line, "AptanaInstall /passive /norestart". Hope this helps.

**Comment by nikchosh** [comment]
+1 (adamtbak workaround helped)

**Comment by aman7** [comment]
hey Adam, thanks man

**Comment by ingo** [comment]
The node requirements should have been removed. Please try the latest installers: https://github.com/aptana/studio3/releases/tag/3.7.0.201807190852

**Comment by aman7** [comment]
it have the same issue

**Comment by ingo** [comment]
This is windows, right?

**Comment by aman7** [comment]
yes, windows 10

**Comment by ingo** [comment]
Can you try the version attached here? https://github.com/aptana/studio3/releases/tag/3.7.1.201807271936

**Comment by ingo** [comment]
Okay, great. We will then mark this issue as closed. We have promoted that version as the latest release.
